name: dispatch test-action workflow
 
on:
  workflow_dispatch:
 
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
 
      - name: dispatch test-action workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CI_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ndsl7109256/Hello/actions/workflows/helloword.yml/dispatches \
            -d '{"ref":"main"}'
